name: Build Release

on:
  workflow_dispatch:
    inputs:
      release-type:
        description: 'Release Type'
        default: 'feature'
        required: false
        type: choice
        options:
          - major
          - feature
          - patch

env:
  WORKSHOP_IDENTIFIER: 3371719217
  WORKSHOP_VISIBILITY: 0

jobs:
  release:
    name: "Create GitHub Release"
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Checkout tags
        run: |
          git config --global user.name 'Chris Kaiser'
          git config --global user.email 'kaiser-chris@users.noreply.github.com'
          git fetch --prune --unshallow --tags

      - name: Get latest version
        id: project
        run: |
          echo "last-version=$(git describe --tags $(git rev-list --tags --max-count=1))" >> $GITHUB_OUTPUT

      - name: Increment release version
        id: increment-version
        uses: christian-draeger/increment-semantic-version@1.2.1
        with:
          current-version: ${{ steps.project.outputs.last-version }}
          version-fragment: ${{ inputs.release-type }}

      - name: Get changes since last tag
        id: commits
        run: |
          {
            echo 'markdown<<EOF'
            echo "$(git log ${{ steps.project.outputs.last-version }}..HEAD --no-merges --pretty=format:' - %s')"
            echo EOF
          } >> "$GITHUB_OUTPUT"

      - name: Set version
        run: |
          sed -i 's/"version" : "${{ steps.project.outputs.last-version }}"/"version" : "${{ steps.increment-version.outputs.next-version }}"/g' mod/.metadata/metadata.json

      - name: Commit Version
        run: |
          git commit -am "Set latest release version"

      - name: Generate Localizations
        shell: bash
        run: |
          (cd script; ./generate-localization.sh english ../mod/)

      - name: Commit Localizations
        run: |
          git commit -am "Updated localizations" || echo "No Localization changes"

      - name: Push Version and Localizations
        run: |
          git push origin

      - name: Create release artifact
        run: |
          (cd mod; zip -r release-${{ steps.increment-version.outputs.next-version }}.zip .)

      - name: Archive release artifact
        uses: actions/upload-artifact@v4
        with:
          name: Release
          path: mod/release-${{ steps.increment-version.outputs.next-version }}.zip

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2.2.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: false
          files: mod/release-${{ steps.increment-version.outputs.next-version }}.zip
          tag_name: ${{ steps.increment-version.outputs.next-version }}
          name: ${{ steps.increment-version.outputs.next-version }}
          body: |
            Released a new version of the **Manaflow: Ankaris Arrival** mod.

            ### Changes:
            ${{ steps.commits.outputs.markdown }}

  publish:
    name: "Publish to Workshop"
    runs-on: ubuntu-latest
    needs: release

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup SteamCMD
        uses: buildalon/setup-steamcmd@v1.0.4

      - name: Create Workshop Metadata
        id: metadata
        shell: bash
        run: |
          (cd script; ./create-release-vdf.sh mod documentation/STEAM_PAGE.bbcode "$WORKSHOP_IDENTIFIER" "$WORKSHOP_VISIBILITY")
          echo "vdf=$(realpath workshop.vdf)" >> "$GITHUB_OUTPUT"

      - name: Publish to Workshop
        shell: bash
        run: |
          steamcmd +login ${{ secrets.WORKSHOP_USERNAME }} ${{ secrets.WORKSHOP_PASSWORD }} +workshop_build_item ${{ steps.metadata.outputs.vdf }} +quit