name: Publish to Workshop

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag'
        required: true
        type: string
      workshop-id:
        description: 'Workshop Identifier'
        required: true
        default: '3371719217'
        type: string

jobs:
  publish:
    name: "Publish to Workshop"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          ref: "${{ inputs.tag }}"

      - name: Create Workshop Metadata
        id: metadata
        shell: bash
        run: |
          (cd script; ./create-release-vdf.sh mod documentation/STEAM_PAGE.bbcode "${{ inputs.workshop-id }}")
          echo "vdf=$(realpath workshop.vdf)" >> "$GITHUB_OUTPUT"
          echo "# Workflow Metadata" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "$(cat < workshop.vdf)" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY

      - name: Setup SteamCMD
        uses: CyberAndrii/setup-steamcmd@v1

      - name: Publish to Workshop
        shell: bash
        run: |
          steamcmd +login ${{ secrets.WORKSHOP_USERNAME }} ${{ secrets.WORKSHOP_PASSWORD }} +workshop_build_item ${{ steps.metadata.outputs.vdf }} +quit